services:
  api:
    volumes:
      - ../../data:/usr/data
    build:
      context: ../
      dockerfile: ./docker/api.Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
  api-test:
    extends:
      service: api
    environment:
      - NODE_ENV=test