services:
  api:
    extends:
      file: api.common.yaml
      service: base
    profiles:
      - production
    environment:
      - NODE_ENV=production
    volumes:
      - ../../data:/usr/data
  api-test:
    extends:
      file: api.common.yaml
      service: base
    profiles:
      - test
    environment:
      - NODE_ENV=test