services:
  ui:
    extends:
      file: ui.common.yaml
      service: base
    profiles:
      - production
  ui-test:
    extends:
      file: ui.common.yaml
      service: base
    profiles:
      - test
    build:
      args:
        VITE_MODE: test
